development:
  sessions:
    default:
      database: ladderboost_development
      hosts:
        - localhost:27017
      options:

test:
  sessions:
    default:
      database: ladderboost_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
